In [12]:
from scipy.sparse import issparse
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

def Preprocess(x):
    cat=x.select_dtypes(include='object').columns
    con=x.select_dtypes(exclude='object').columns

    num_pipe=Pipeline(steps=[('impute',SimpleImputer(strategy='median')),('scalar',MinMaxScaler())])
    cat_pipe=Pipeline(steps=[('impute',SimpleImputer(strategy='most_frequent')),('Encoder',OneHotEncoder())])

    pre=ColumnTransformer([('Num_pipe',num_pipe,con),('cat_pipe',cat_pipe,cat)])

    x1=pre.fit_transform(x)

    if issparse(x1):
        x1=x1.toarray()
    x2=pd.DataFrame(x1,columns=pre.get_feature_names_out())
    return x2

# data collection

In [1]:
import os
os.chdir('D:Data_sets/')

In [2]:
import pandas as pd
df=pd.read_csv('Cars93.csv')
df

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,NaN,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,NaN,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,NaN,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

In [3]:
df.columns

Index(['id', 'Manufacturer', 'Model', 'Type', 'Min.Price', 'Price',
       'Max.Price', 'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain',
       'Cylinders', 'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile',
       'Man.trans.avail', 'Fuel.tank.capacity', 'Passengers', 'Length',
       'Wheelbase', 'Width', 'Turn.circle', 'Rear.seat.room', 'Luggage.room',
       'Weight', 'Origin', 'Make'],
      dtype='object')

In [5]:
df[['Man.trans.avail']]

   Man.trans.avail
0              Yes
1              Yes
2              Yes
3              Yes
4              Yes
..             ...
88             Yes
89             Yes
90             Yes
91             Yes
92             Yes

[93 rows x 1 columns]

In [7]:
df.shape

(93, 28)

# Exploratory data analysis

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  93 non-null     int64
 1   Manufacturer        93 non-null     object
 2   Model               93 non-null     object
 3   Type                93 non-null     object
 4   Min.Price           93 non-null     float64
 5   Price               93 non-null     float64
 6   Max.Price           93 non-null     float64
 7   MPG.city            93 non-null     int64
 8   MPG.highway         93 non-null     int64
 9   AirBags             56 non-null     object
 10  DriveTrain          93 non-null     object
 11  Cylinders           93 non-null     object
 12  EngineSize          93 non-null     float64
 13  Horsepower          93 non-null     int64
 14  RPM                 93 non-null     int64
 15  Rev.per.mile        93 non-null     int64
 16  Man.trans.avail     93 non-null     object
 17  Fuel.tank.capacity  93 non-null     float64
 18  Passengers          93 non-null     int64
 19  Length              93 non-null     int64
 20  Wheelbase           93 non-null     int64
 21  Width               93 non-null     int64
 22  Turn.circle         93 non-null     int64
 23  Rear.seat.room      91 non-null     float64
 24  Luggage.room        82 non-null     float64
 25  Weight              93 non-null     int64
 26  Origin              93 non-null     object
 27  Make                93 non-null     object
dtypes: float64(7), int64(12), object(9)
memory usage: 20.5+ KB

In [13]:
x=df.drop(['Man.trans.avail','id'],axis=1)
y=df['Man.trans.avail']

In [14]:
x1=Preprocess(x)
x1

,Num_pipe__Min.Price,Num_pipe__Price,Num_pipe__Max.Price,Num_pipe__MPG.city,Num_pipe__MPG.highway,Num_pipe__EngineSize,Num_pipe__Horsepower,Num_pipe__RPM,Num_pipe__Rev.per.mile,Num_pipe__Fuel.tank.capacity,...,cat_pipe__Make_Toyota Camry,cat_pipe__Make_Toyota Celica,cat_pipe__Make_Toyota Previa,cat_pipe__Make_Toyota Tercel,cat_pipe__Make_Volkswagen Corrado,cat_pipe__Make_Volkswagen Eurovan,cat_pipe__Make_Volkswagen Fox,cat_pipe__Make_Volkswagen Passat,cat_pipe__Make_Volvo 240,cat_pipe__Make_Volvo 850
0,0.160207,0.155963,0.151179,0.322581,0.366667,0.170213,0.346939,0.925926,0.644764,0.224719,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.581395,0.486239,0.427184,0.096774,0.166667,0.468085,0.591837,0.629630,0.416838,0.494382,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.496124,0.398165,0.338419,0.161290,0.200000,0.382979,0.477551,0.629630,0.394251,0.432584,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.622739,0.555963,0.509015,0.129032,0.200000,0.382979,0.477551,0.629630,0.498973,0.668539,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.439276,0.414679,0.392510,0.225806,0.333333,0.531915,0.624490,0.703704,0.503080,0.668539,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,0.255814,0.225688,0.205270,0.064516,0.033333,0.319149,0.220408,0.259259,0.655031,0.668539,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
89,0.281654,0.231193,0.201110,0.193548,0.333333,0.212766,0.322449,0.740741,0.560575,0.522472,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
90,0.418605,0.291743,0.219140,0.096774,0.166667,0.382979,0.502041,0.740741,0.437372,0.522472,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
91,0.390181,0.280734,0.216366,0.193548,0.266667,0.276596,0.240816,0.592593,0.367556,0.370787,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
92,0.467700,0.354128,0.285714,0.161290,0.266667,0.297872,0.461224,0.888889,0.406571,0.567416,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

# Train Test Split

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x1,y,test_size=0.2,random_state=23)


# Model

In [16]:
from sklearn.linear_model import LogisticRegression
la=LogisticRegression()
la.fit(x_train,y_train)

LogisticRegression()

# Evaluate Model

In [18]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

# Training Data Evaluation

In [21]:
y_pred_train=la.predict(x_train)

In [22]:
Classification_evaluate(y_pred_train,y_train)

********************************************************************************
Accuracy: 1.0
____________________________________________________________________________________________________
Classification Report:
               precision    recall  f1-score   support

          No       1.00      1.00      1.00        23
         Yes       1.00      1.00      1.00        51

    accuracy                           1.00        74
   macro avg       1.00      1.00      1.00        74
weighted avg       1.00      1.00      1.00        74

____________________________________________________________________________________________________
Confusion Matrix:
 [[23  0]
 [ 0 51]]
********************************************************************************

********************************************************************************
Accuracy: 1.0
____________________________________________________________________________________________________
Classification Report:
               precision    recall  f1-score   support

          No       1.00      1.00      1.00        23
         Yes       1.00      1.00      1.00        51

    accuracy                           1.00        74
   macro avg       1.00      1.00      1.00        74
weighted avg       1.00      1.00      1.00        74

____________________________________________________________________________________________________
Confusion Matrix:
 [[23  0]
 [ 0 51]]
********************************************************************************